version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
- package-ecosystem: terraform
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/tests"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: terraform
  directory: "/tests/vault-py2"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: terraform
  directory: "/tests/vault-py3"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
